### ISSUE TITLE
Adding Glyphs for Powerline etc?

### ISSUE THREAD

**Issue by dan-and** [BourgeoisBear/DaddyTimeMono#1]
Hey Jason, 

I really like your DaddyTimeMono Font. I use it for quite a long time already, but recently I switched from bash to zsh and saw that glyphs for powerline (See: https://github.com/robbyrussell/oh-my-zsh ) 

I used the fontforge font-patcher script from https://github.com/ryanoasis/nerd-fonts#font-patcher which worked fine with your font. 

Would it be possible to add it as default or add your font to either nerd-fonts ( https://github.com/ryanoasis/nerd-fonts ) or powerline-fonts (https://github.com/powerline/fonts )?

Cheers,

Daniel

**Comment by BourgeoisBear** [comment]
Thanks Daniel!

I *think* most systems do fallbacks for missing glyphs (I look at a lot of Japanese script, even though DaddyTimeMono has no Japanese glyphs), so I'm not sure that I fully understand the problem.

Completely OK to upload a patched one-off version to nerd-fonts and powerline-fonts though.  And I'm not averse to bundling those features in the main repository.  Just want to determine if there is a simpler way to accomplish the same goal.

**Comment by aasutossh** [comment]
Could close this issue now. DaddyTimeMono is available in the nerd-fonts repo.
