### ISSUE TITLE
The backtick character is a bit high?

### ISSUE THREAD

**Issue by tulemizh** [BourgeoisBear/DaddyTimeMono#4]
I am using **DaddyTimeMono** on an Ubuntu machine. I seen to see the **backtick** character is a bit high? It almost touches the text above. Could you edit it?

![image](https://user-images.githubusercontent.com/77402392/111898800-ba2af800-8a5a-11eb-8e5f-1cf532cdf439.png)

Thank you so much.

Regards,
Tu Le.

**Comment by BourgeoisBear** [comment]
yes.  give me a day or so to get to it.  any other tweaks?

**Comment by tulemizh** [comment]
Not as of now, I am completely satisfied with the other things about **DaddyTimeMono**.

Regards,
Tu Le.

**Comment by BourgeoisBear** [comment]
try it now

**Comment by tulemizh** [comment]
It looks great. Thank you very much :+1: 

![image](https://user-images.githubusercontent.com/77402392/112160339-a4653080-8c1c-11eb-879e-65fa8a2d8192.png)

Regards,
Tu Le.
