### ISSUE TITLE
Not valid

### ISSUE THREAD

**Issue by thistlillo** [BourgeoisBear/DaddyTimeMono#5]
My Windows 10, today 2021-04-06, says that the .ttf is not in a valid format.

**Comment by BourgeoisBear** [comment]
@thistlillo I'll check into it.  Probably forgot to "round to int" before last build.  Give me a day or two.

**Comment by BourgeoisBear** [comment]
@thistlillo try it now.  Verified on Win 7, no problems there.

**Comment by thistlillo** [comment]
Unfortunately, my windows 10 pro keeps saying it is not valid :-(
![font](https://user-images.githubusercontent.com/6717655/115341995-d335de80-a1a9-11eb-8a98-742fb9dea5bc.png)

**Comment by BourgeoisBear** [comment]
@thistlillo I'll need to spin up a win10 vm to dig into this, so might be a week or two 'til I get to it.

**Comment by thistlillo** [comment]
Thank you, I appreciate but take your time. I am very curious to test your font, but nothing important depends on it.

**Comment by kclevenger** [comment]
Linux fc does not recognize it either

**Comment by BourgeoisBear** [comment]
@kclevenger  @thistlillo 

Just pushed v1.2.1.  Again, no problem on Debian 10, Windows 7, or OSX BigSur.

If it is still not working, please supply as much information as you can.

Thx.

JS

**Comment by kclevenger** [comment]
Works for me
DaddyTimeMono.ttf: DaddyTimeMono:style=Book

**Comment by thistlillo** [comment]
Unfortunately, I keep receiving the same error.

Double click fails:
![daddy-mono-dclick](https://user-images.githubusercontent.com/6717655/117261569-937d2100-ae50-11eb-9a13-0bef7e50bf55.PNG)

Installing in Settings->Font Settings (by drag and drop on target area) fails:
![daddy-mono](https://user-images.githubusercontent.com/6717655/117261666-b3ace000-ae50-11eb-852d-6828355464fd.PNG)

Dropping the file on the application "Character Map UWP" fails:
![daddy-mono2](https://user-images.githubusercontent.com/6717655/117261776-d3dc9f00-ae50-11eb-83c2-e7c67a91cf6c.PNG)

I do not know how I might help you in fixing the issue, if you want me to perform specific tests, just ask, I will gladly help.

Thank you very much.

**Comment by BourgeoisBear** [comment]
@thistlillo thanks for the screencaps.  I'll run the font through a few different validators and see what I can find.  So far, Win 7, Debian 10, and OS X Big Sur are all A-OK.

**Comment by BourgeoisBear** [comment]
@thistlillo had some time to dig into this.  There were a few validation errors.  Switching to `.OTF` made them go away.  Please let me know if this fixes things on Win 10.

Thx.

JS

**Comment by thistlillo** [comment]
THANK YOU!
Not it works perfectly.

It is a nice, beautiful, pleasant font: congratulations and thanks!
