### ISSUE TITLE
Reenable ttf output

### ISSUE THREAD

**Issue by mgred** [BourgeoisBear/DaddyTimeMono#6]
It's stated in the `READEME.md`, that the TTF file lives in the `./build` directory but only an OTF file is placed there. From the `make.sh` script it seems the build of the TTF file is commented out. Is it possible to reenable the build and place the TTF file in the `./build` directory?

If not, I gladly update the `README.md` that an **OTF** file lives in `./build`.

**Comment by BourgeoisBear** [comment]
Switched to OTF a few versions back to handle reference intersections, so updated the readme.
thx
JS
